sudo: required
services:
    - docker
before_install:  
    - gem install bundler --pre
    - docker build -t luhansmilex/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true luhansmilex/react-test npm run test

after_success:
    - docker build -t luhansmilex/multi-client ./client
    - docker build -t luhansmilex/multi-nginx ./nginx
    - docker build -t luhansmilex/multi-server ./server
    - docker build -t luhansmilex/multi-worker ./worker
    # Log in to the docker CLI
    - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD docker.io  
    - docker login  
    - docker push luhansmilex/multi-client
    - docker push luhansmilex/multi-nginx
    - docker push luhansmilex/multi-server
    - docker push luhansmilex/multi-worker